server:
  port: 8761


peer2:
  server:
      host: peer2
      port: 8762


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
        defaultZone: http://blackfat:blackfat@${peer2.server.host}:${peer2.server.port}/eureka/