spring:
  application:
    name: microservice-eureka

eureka:
  server:
    enable-self-preservation: false
management:
  security:
    enabled: false

security:
  basic:
    enabled: true
  user:
    name: blackfat
    password: blackfat






