spring:
  application:
    name: consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://blackfat:blackfat@101.132.177.27:8761/eureka/,http://blackfat:blackfat@101.132.177.27:8762/eureka/
server:
  port: 9999

feign:
    hystrix:
       enabled: true