spring:
  application:
    name: api-gateway
server:
  port: 5000



zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: base-service
    api-b:
      path: /api-b/**
      serviceId: consumer-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/





